### ISSUE TITLE
What to do the very first time the app loads

### ISSUE THREAD

**Issue by smpcole** [smpcole/days-since#9]
Idea: nothing will be found in application documents directory, so do the following:
1. Create a new counter with default values and save it as counter0.
2. Save a value of 0 to currentView (if #6 is supported).

**Comment by ZaneH** [comment]
This issue doesn't include much description, and I'm not sure I'm understanding it 100% but have you looked into `NSUserDefaults`?

**Comment by smpcole** [comment]
The issue is that when the app loads it tries to load certain data (e.g., the stored counter value) from disk using `NSKeyedUnarchiver`.  But the first time the app loads the files will not be found on disk, so in its current state the app would probably crash.

**Comment by ZaneH** [comment]
``` objective-c
NSData *dataToGet = [[NSUserDefaults standardUserDefaults] objectForKey:@"storedDataForQuestion"];
if ([NSKeyedUnarchiver unarchiveObjectWithData:dataToGet]) {
    // interpret the data
} else {
    // do nothing. create the data maybe?
}
```

This should solve the problem without any changes to the project.
